version: '3'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    stdin_open: true
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./web:/app
      - /app/node_modules
    command: yarn dev